# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(587, 380)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.staticsBox = QtWidgets.QGroupBox(self.centralwidget)
        self.staticsBox.setGeometry(QtCore.QRect(10, 10, 191, 91))
        self.staticsBox.setFlat(False)
        self.staticsBox.setObjectName("staticsBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.staticsBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.packetsLabel = QtWidgets.QLabel(self.staticsBox)
        self.packetsLabel.setObjectName("packetsLabel")
        self.verticalLayout.addWidget(self.packetsLabel)
        self.ethPacketsLabel = QtWidgets.QLabel(self.staticsBox)
        self.ethPacketsLabel.setObjectName("ethPacketsLabel")
        self.verticalLayout.addWidget(self.ethPacketsLabel)
        self.arpPacketsLabel = QtWidgets.QLabel(self.staticsBox)
        self.arpPacketsLabel.setObjectName("arpPacketsLabel")
        self.verticalLayout.addWidget(self.arpPacketsLabel)
        self.entropyBox = QtWidgets.QGroupBox(self.centralwidget)
        self.entropyBox.setGeometry(QtCore.QRect(10, 110, 191, 71))
        self.entropyBox.setFlat(False)
        self.entropyBox.setObjectName("entropyBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.entropyBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ethEntropyLabel = QtWidgets.QLabel(self.entropyBox)
        self.ethEntropyLabel.setObjectName("ethEntropyLabel")
        self.verticalLayout_2.addWidget(self.ethEntropyLabel)
        self.arpEntropyLabel = QtWidgets.QLabel(self.entropyBox)
        self.arpEntropyLabel.setObjectName("arpEntropyLabel")
        self.verticalLayout_2.addWidget(self.arpEntropyLabel)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 587, 27))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuCatuper = QtWidgets.QMenu(self.menubar)
        self.menuCatuper.setObjectName("menuCatuper")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionStart = QtWidgets.QAction(MainWindow)
        self.actionStart.setObjectName("actionStart")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionStop = QtWidgets.QAction(MainWindow)
        self.actionStop.setEnabled(False)
        self.actionStop.setObjectName("actionStop")
        self.actionReset = QtWidgets.QAction(MainWindow)
        self.actionReset.setObjectName("actionReset")
        self.actionInterval = QtWidgets.QAction(MainWindow)
        self.actionInterval.setObjectName("actionInterval")
        self.menuFile.addAction(self.actionQuit)
        self.menuCatuper.addAction(self.actionInterval)
        self.menuCatuper.addAction(self.actionStart)
        self.menuCatuper.addAction(self.actionStop)
        self.menuCatuper.addAction(self.actionReset)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuCatuper.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sniffer"))
        self.staticsBox.setTitle(_translate("MainWindow", "Statics"))
        self.packetsLabel.setText(_translate("MainWindow", "Packets: 0"))
        self.ethPacketsLabel.setText(_translate("MainWindow", "Ethernet Packets: 0"))
        self.arpPacketsLabel.setText(_translate("MainWindow", "ARP Packets: 0"))
        self.entropyBox.setTitle(_translate("MainWindow", "Entropy"))
        self.ethEntropyLabel.setText(_translate("MainWindow", "Ethernet: -1"))
        self.arpEntropyLabel.setText(_translate("MainWindow", "ARP: -1"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuCatuper.setTitle(_translate("MainWindow", "Capture"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionStart.setText(_translate("MainWindow", "Start"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionStop.setText(_translate("MainWindow", "Stop"))
        self.actionReset.setText(_translate("MainWindow", "Reset"))
        self.actionInterval.setText(_translate("MainWindow", "Interval"))

