#!/usr/bin/env python2

import sys

from PyQt4.QtCore import *
from PyQt4.QtGui import *
from MainWindow import MainWindow

if __name__ == '__main__':
	app = QApplication(sys.argv)
	window = MainWindow()
	window.show()
	app.exec_()
